会場を株式会社インプレスに更新した
BansheeNorun02/ichiyasaGitSample pull request #1
Opened 2024-09-11 01:09 UTC by BansheeNorun02

###変更内容
イベント開催会場を「株式会社インプレス」に更新しました。

###背景
「株式会社インプレス」さんがイベント会場を提供してくださることになりました。

2024-09-11 01:19 UTC, BansheeNorun02 commented
ahahahahahahaahah

2024-09-11 01:44 UTC, takahashi123456789 commented
html

2024-09-11 01:46 UTC, ookubo12345678910 commented
321

2024-09-11 01:47 UTC, enbi3 commented
０４２６
たんじょ

2024-09-11 01:47 UTC, BansheeNorun02 commented
修正ありがとうございます！！！！！問題ないのでマージします。

2024-09-11 01:49 UTC, enbi3 commented
> 修正ありがとうございます！！！！！問題ないのでマージしません。女大好き！！！！！マジで！！！！！！！！

2024-09-11 01:50 UTC, BansheeNorun02 commented
うるさいうるさいうるさい

2024-09-11 01:52 UTC, enbi3 commented
lol

2024-09-11 01:53 UTC, ookubo12345678910 commented
Zeus
Oner
Faker
Gumayusi
Keria

2024-09-11 01:59 UTC, takahashi123456789 commented on index.html
> +                           株式会社インプレス イベントセミナー会場</p>
System.out.print(「株式会社インプレス」と精子な表記にしていただけますか？)

2024-09-11 02:01 UTC, ookubo12345678910 requested changes
yametene👍

2024-09-11 02:01 UTC, ookubo12345678910 commented on index.html
> +                           株式会社インプレス イベントセミナー会場</p>
yamatene👍

2024-09-11 02:01 UTC, enbi3 requested changes
naositene

2024-09-11 02:01 UTC, enbi3 commented on index.html
> +                           株式会社インプレス イベントセミナー会場</p>
教科書とちがいますよ

2024-09-11 02:02 UTC, BansheeNorun02 commented
うるさいだまれ

2024-09-12 00:51 UTC, BansheeNorun02 commented
damare

2024-09-12 00:55 UTC, merged